# Set dependencies and functions

In [1]:
import string
import nltk
from nltk.corpus import stopwords
from nltk import FreqDist
import pandas as pd
from nltk.tokenize import word_tokenize
import numpy as np

from lets_plot import *
LetsPlot.setup_html()

In [2]:
stop_words = set(stopwords.words("english"))
stop_words.update(["also", "'s", "us", "must", "many"])

def clean_our_text_pythonian(text):
    tokens = word_tokenize(text)
    return " ".join(
        [word for word in tokens 
         if word.lower() not in stop_words 
         and not word.isdigit() 
         and word not in string.punctuation]
    )

# Import data

In [3]:
Text = open("Lawrence Wong Speech.txt").read()

Text

# Data Wrangling
## Remove stopwords, punctuations, lower text

In [4]:
cleaned_text =\
(
    clean_our_text_pythonian(Text)
)

cleaned_text

## Tokenise your text so the machine can process it

In [5]:
tokens=\
(
    nltk
    .word_tokenize(cleaned_text
                  .lower()
                  )
)

tokens

# Calculate and model frequency and 20 most common words

In [6]:
# Calculate frequency distribution
fdist = FreqDist(tokens)

# Find the 20 most common words
top_20_words=\
(
    pd
    .DataFrame((fdist.most_common(20)))
)
top_20_words_renamed =\
(
    top_20_words.rename(columns = {0: "words", 1: "volume"})
)

In [7]:
top_20_words_renamed

           words  volume
0      singapore      84
1        support      64
2             ai      54
3   singaporeans      39
4           year      37
5       continue      34
6            new      33
7      companies      31
8           help      30
9       families      29
10           one      28
11       workers      28
12        global      26
13         build      26
14    strengthen      26
15       provide      26
16        skills      26
17    government      25
18          work      24
19        growth      23

In [8]:
top_20_words_renamed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   words   20 non-null     object
 1   volume  20 non-null     int64
dtypes: int64(1), object(1)
memory usage: 452.0+ bytes

In [9]:
top_20_words_renamed.columns

Index(['words', 'volume'], dtype='object')

# Data visualisation (top 20 keywords used during speech)

In [10]:
top_20_keywords_SG_budget_2026=\
(
    ggplot(top_20_words_renamed,
           aes(x = "words",
               y = "volume")
          )
    + geom_bar(stat = "identity")
    # + coord_flip()
    + labs(title = "Frequency of words in Prime Minister Lawrence Wong 2026 Budget Speech",
           subtitle = "Top 3 words are 'Singapore', 'Support' and 'AI'",
           caption = "Source: Youtube Transcript")
    + geom_segment(x = 2, xend = 2,
                   y = 65, yend = 60, 
                   arrow = arrow(length = 10, 
                                 type='closed'), 
                   color = "red"
                  )
    + geom_segment(x = 1, xend = 1,
                   y = 75, yend = 70, 
                   arrow = arrow(length = 10, 
                                 type='closed'), 
                   color = "red"
                  )
    + geom_segment(x = 0, xend = 0,
                   y = 95, yend = 90, 
                   arrow = arrow(length = 10, 
                                 type='closed'), 
                   color = "red"
                  )
    + theme_classic()
    + ggsize(1700,800)
)

In [11]:
top_20_keywords_SG_budget_2026

# Model the top 3 most used keywords

In [12]:
from nltk.draw.dispersion import dispersion_plot

In [13]:
# Based on the top 3 words usage, let's see dispersion too
finance_words_of_interest = ["singapore", "support", "ai"]

In [14]:
rows = []

rows =\
    [
        {"index": idx,
         "word": tok}
        for idx, tok
        in enumerate(tokens)
        if tok in finance_words_of_interest
    ]

df_wong_2026 =\
(
    pd
    .DataFrame(rows)
)

In [15]:
df_wong_2026

     index       word
0      176         ai
1      346  singapore
2      415    support
3      423  singapore
4      442    support
..     ...        ...
197   6278  singapore
198   6420  singapore
199   6432  singapore
200   6480  singapore
201   6486    support

[202 rows x 2 columns]

# Using <mark>dispersion plot</mark> to find out the top 3 keywords frequency and timeseries. Time elapsed between his usage of those target words.

In [16]:
dispersion_plot_for_wong_2026 =\
(
    ggplot(df_wong_2026)
    + geom_point(aes(x = "index",
                     y = "word",
                     color = "word",
                     shape = "word"),
                 size = 3
                )
    + labs(title = "Prime Minister Lawrence Wong 2026 Budget Speech",
           subtitle = "PM was basically rapping about AI at one point. Crazy.",
           x = "Token Index (Look at the Intervals)",
           y = "Budget Speech Words of Interest")
    + ggsize(1700,800)
)

In [17]:
dispersion_plot_for_wong_2026

In [18]:
dispersion_plot_for_wong_2026.to_html("index.html")

'/Users/zhenghanong/dddm/Module 5 (Natural Language Processing (NLP), Sentiment Analysis, and Applied LLMs)/index.html'

# Model the keywords on business and family topics

In [19]:
words_of_interest = ["companies", "workers", "families"]

In [20]:
rows = []

rows =\
    [
        {"index": idx,
         "word": tok}
        for idx, tok
        in enumerate(tokens)
        if tok in words_of_interest
    ]

df_workervsfamily_2026 =\
(
    pd
    .DataFrame(rows)
)

# Using <mark>dispersion plot</mark> to find out the business topic vs family topic frequency and timeseries. Time elapsed between his usage of those target words.

In [21]:
dispersion_plot_for_busiess_vs_families_2026 =\
(
    ggplot(df_workervsfamily_2026)
    + geom_point(aes(x = "index",
                     y = "word",
                     color = "word",
                     shape = "word"),
                 size = 3
                )
    + labs(title = "Business vs Family Support",
           subtitle = "From this data it seems there is more focus on supporting the Singapore labour market compared to families",
           x = "Token Index (Look at the Intervals)",
           y = "Budget Speech Words of Interest")
    + ggsize(1700,800)
)

In [22]:
dispersion_plot_for_busiess_vs_families_2026